name: ci-app-workflow
on: push
jobs:
  bild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-node@v3
      - run: make setup
      - run: make test
      - run: make lint
