name: ci-app-workflow
on: push
permissions:
  contents: read
jobs:
  bild:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: action/setup-node@v3
      - run: make setup
      - run: make test
      - run: make lint
